<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Du måste vara inloggad för att registrera dig. Har du inte ett konto är det bara att registrera sig!' => 'You need to be logged in in order to register. If you don\'t have an account you can create one by clicking Register in the upper right-hand corner!',
  'Anmäl dig' => 'Register',
  'Anmälan gjord' => 'Registered on',
  'Anmälning' => 'Registration',
  'Anmälning till {lanName}' => 'Register for {lanName}',
  'Anmälningar till {lanName}' => 'Registrations for {lanName}',
  'Antal registrerade hittills' => 'Registrations so far',
  'E-post' => 'E-mail',
  'Information' => 'Information',
  'Jag använder en' => 'I\'m using a',
  'Jag tänker delta<br />i dessa tävlingar (slutlig allmän görs under LAN {link})' => 'I will participate in the following competitions (final registration is done during LAN {link})',
  'Namn' => 'Name',
  'Nick' => 'Nickname',
  'Penis längre än {length}"?' => 'Penis longer than {length}"?',
  'har ej deltagit förut' => 'hasn\'t participated before',
  'har ej giltig betalning' => 'doesn\'t have a valid payment',
  'härifrån' => 'from here',
);
