version: "3"

services:
  tlklan:
    image: tlk/tlklan:latest
    build: .
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - ./submissions:/var/www/html/tlklan/files/submissions
      - ./runtime:/var/www/html/tlklan/protected/runtime
    env_file:
      - .env

  tlklan-db:
    image: "tutum/mysql:5.6"
    environment:
      ON_CREATE_DB: tlk_lan
      MYSQL_PASS: tlklan
      STARTUP_SQL: /tmp/mysql-script/startup.sql
    volumes:
      - ./provisioning/sql:/tmp/mysql-script
      - ./db:/var/lib/mysql
